const BOOK_GENRES = {
  ACTION: "ACTION",
  FANTASY: "FANTASY",
  HISTORY: "HISTORY",
  HORROR: "HORROR",
  HUMOR: "HUMOR",
  MYSTERY: "MYSTERY",
  ROMANCE: "ROMANCE",
  SCIENCE: "SCIENCE",
  THRILLER: "THRILLER",
}
const data_sample = {
  ACTION: [
    {
      id: 1,
      title: "Across the Pond",
      author: "Michael McCormick",
      description: `Across the Pond" is a heartfelt novel capturing the transatlantic bond between two teenagers, exploring love, friendship, and the challenges of long-distance relationships between America and England.`,
      image: "https://m.media-amazon.com/images/I/81nu8QnXBuL._AC_UY327_FMwebp_QL65_.jpg",
      genre: BOOK_GENRES.ACTION,
      language: "en",
      rating: 4,
      review: 10,
      price: 200,
      currency: 'Rs',
      countInStock: 300,
      pdf: '/pdfs/genres/Action/Across.pdf',
      userReviews: [
        { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
        { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
      ],  
    },
    {
        id: 2,
        title: "Agent with a History (Book One)",
        author: "Guy S Santon",
        description: "Agent with a History (Book One) dives into a world of intrigue and suspense, following the adventures of a mysterious agent on a thrilling mission.",
        image: "https://m.media-amazon.com/images/I/91Sov5pj6zL._AC_UY327_FMwebp_QL65_.jpg",
        genre: "ACTION",
        language: "vi",
        rating: 4.14,
        review: 10,
        price: 120,
        currency: "Rs",
        countInStock: 300,
        pdf: "/pdfs/genres/Action/Agent with a History (Book One).pdf",
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
      {
        id: 3,
        title: "Direct Action",
        author: "Tom Fitzgerald",
        description: "Direct Action takes readers on a high-stakes adventure, filled with suspense and unexpected twists, as a team of operatives navigates through complex challenges.",
        image: "https://m.media-amazon.com/images/I/81P3ke4oEEL._AC_UY327_FMwebp_QL65_.jpg",
        genre: "ACTION",
        language: "vi",
        rating: 4.55,
        review: 10,
        price: 100,
        currency: "Rs",
        countInStock: 300,
        pdf: "/pdfs/genres/Action/Direct Action.pdf",
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
      {
        id: 4,
        title: "House Of Refuge",
        author: "Michael A DiBaggio",
        description: "House Of Refuge paints a gripping narrative of survival and resilience amidst unforeseen challenges, as characters navigate through unexpected circumstances.",
        image: "https://m.media-amazon.com/images/I/61SMBiRkspL._SY522_.jpg",
        genre: "ACTION",
        language: "en",
        rating: 5,
        review: 8,
        price: 200,
        currency: "Rs",
        countInStock: 300,
        pdf: "/pdfs/genres/Action/House Of Refuge.pdf",
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
      {
        id: 5,
        title: "Keyhole Island",
        author: "Charles Coiro",
        description: "Keyhole Island unravels a mysterious tale set on an enigmatic island, brimming with adventure and secrets waiting to be uncovered.",
        image: "https://m.media-amazon.com/images/I/71R8gRZMM7L._AC_UY327_FMwebp_QL65_.jpg",
        genre: "ACTION",
        language: "en",
        rating: 4.26,
        review: 10,
        price: 400,
        currency: "Rs",
        countInStock: 300,
        pdf: "/pdfs/genres/Action/Keyhole Island.pdf",
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
  ],
  HISTORY: [
    {
        id: 1,
        title: "A Daughter Of The Snows",
        author: "Jack London",
        description: `"Daughter of the Snows" is a Jack London novel set in the Yukon during the Gold Rush, featuring Frona Welse, a courageous and independent woman navigating the challenges of a rugged, male-dominated environment. It explores themes of gender roles, adventure, and survival against the harsh backdrop of the Klondike.`,
        image: "https://m.media-amazon.com/images/I/81yElX3LZFS._AC_UY327_FMwebp_QL65_.jpg",
        genre: BOOK_GENRES.HISTORY,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 130,
        currency: 'Rs',
        countInStock: 300,
        pdf: '/pdfs/genres/History/A Daughter Of The Snows.pdf',
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
      {
        id: 2,
        title: "A Pirate's Wife",
        author: "Lynelle Clark",
        description: `"A Pirate's Wife" is a novel by Lynelle Clark, following the tale of Sarah Ramsey, who falls in love with a notorious pirate captain. As she immerses herself in a world of danger and adventure on the high seas, Sarah must navigate treacherous waters, loyalty, and her own desires while standing by her husband's side in his perilous pursuits.`,
        image: "https://m.media-amazon.com/images/I/81D7n7DU9eL._AC_UY327_FMwebp_QL65_.jpg",
        genre: BOOK_GENRES.HISTORY,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 150,
        currency: 'Rs',
        countInStock: 300,
        pdf: '/pdfs/genres/History/A Pirate\'s Wife.pdf',
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
      {
        id: 3,
        title: "An Atheist's Bible",
        author: "Kurtis Sunday",
        description: `"An Atheist's Bible" by Joan Konner is a thought-provoking novel following Roberta Klein, an atheist philosopher, as she navigates life's meaning and moral complexities without religious belief, challenging conventional ideas of spirituality and existence.`,
        image: "https://m.media-amazon.com/images/I/614SKctbX1L._AC_UY327_FMwebp_QL65_.jpg",
        genre: BOOK_GENRES.HISTORY,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 170,
        currency: 'Rs',
        countInStock: 0,
        pdf: '/pdfs/genres/History/An Atheist\'s Bible.pdf',
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
      {
        id: 4,
        title: "Britannia",
        author: "Letitia Coyne",
        description: `"Britannia" refers to the Roman name for the island of Great Britain. It signifies the period when Britain was part of the Roman Empire, showcasing significant cultural, political, and historical influence on the island. This term is often used to evoke a sense of ancient Roman rule and its impact on Britain's development and identity.`,
        image: "https://m.media-amazon.com/images/I/41gaK+XCnRL.jpg",
        genre: BOOK_GENRES.ACTION,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 160,
        currency: 'Rs',
        countInStock: 0,
        pdf: '/pdfs/genres/Hostory/Britannia.pdf',
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
  ],
  FANTASY: [
    {
        id: 1,
        title: "A Christmas Carol",
        author: "Charles Dickens",
        description: "A classic tale portraying the transformation of Ebenezer Scrooge through ghostly visits during Christmas.",
        image: "https://m.media-amazon.com/images/I/81thZaP7J4L._AC_UY327_FMwebp_QL65_.jpg",
        genre: BOOK_GENRES.FANTASY,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 200,
        currency: 'Rs',
        countInStock: 300,
        pdf: '/pdfs/genres/Fantasy/A Christmas Carol.pdf',
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
      {
        id: 2,
        title: "A Connecticut Yankee in King Arthur's Court",
        author: "Mark Twain",
        description: "Experience a 19th-century American transported back in time to King Arthur's era, navigating the challenges and humorously altering history.",
        image: "https://m.media-amazon.com/images/I/71jzxXQiTSL._AC_UY327_FMwebp_QL65_.jpg",
        genre: BOOK_GENRES.FANTASY,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 300,
        currency: 'Rs',
        countInStock: 0,
        pdf: '/pdfs/genres/Fantasy/A Connecticut Yankee in King Arthur\'s Court.pdf',
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
      {
        id: 3,
        title: "A Voyage to Arcturus",
        author: "David Lindsay",
        description: "Delve into an interstellar adventure exploring philosophical themes and encountering alien civilizations.",
        image: "https://m.media-amazon.com/images/I/71tDXdGmrAL._AC_UY327_FMwebp_QL65_.jpg",
        genre: BOOK_GENRES.FANTASY,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 280,
        currency: 'Rs',
        countInStock: 0,
        pdf: '/pdfs/genres/Fantasy/A Voyage to Arcturus.pdf',
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
      {
        id: 4,
        title: "Alice's Adventures in Wonderland",
        author: "Lewis Carroll",
        description: "Follow Alice into the whimsical Wonderland filled with peculiar creatures and nonsensical adventures.",
        image: "https://m.media-amazon.com/images/I/81M08HZxk2L._AC_UY327_FMwebp_QL65_.jpg",
        genre: BOOK_GENRES.FANTASY,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 550,
        currency: 'Rs',
        countInStock: 0,
        pdf: '/pdfs/genres/Fantasy/Alice\'s Adventures in Wonderland.pdf',
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
      {
        id: 5,
        title: "Celtic Evil",
        author: "Sierra Rose",
        description: "Uncover ancient Celtic secrets, dark magic, and thrilling adventures in a mystical world.",
        image: "https://m.media-amazon.com/images/I/71nakPLrIWL._AC_UY327_FMwebp_QL65_.jpg",
        genre: BOOK_GENRES.FANTASY,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 180,
        currency: 'Rs',
        countInStock: 0,
        pdf: '/pdfs/genres/Fantasy/Celtic Evil.pdf',
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
  ],
  HORROR: [
    {
      id: 1,
      title: "Abigail's Window",
      author: "Michael Hayes",
      description: `n a powerful story about learning to be proud of one's true self and rising above bullies, sixth-grader Abby is sick of the “medium girls,” who weigh the right amount and say all the right things, and of her parents, who are on her case about dieting and fitting in.`,
      image: "https://m.media-amazon.com/images/I/71jJtPBL-YL._AC_UY327_FMwebp_QL65_.jpg",
      genre: BOOK_GENRES.HORROR,
      language: "en",
      rating: 4.26,
      review: 10,
      price: 200,
      currency: 'Rs',
      countInStock: 300,
      pdf: `/pdfs/genres/Horror/Abigail's Window.pdf`,
      userReviews: [
        { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
        { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
      ],  
    },
    {
      id: 2,
      title: "As Darkness Breaks (Book One)",
      author: "Jonny Newell",
      description: `investigation into a journalist's disappearance sends her down an unexpectedly twisted path in a riveting thriller by the author of Shadow Sands. Kate Marshall's fledgling PI agency takes off when she and her partner, Tristan Harper, are hired for their first big case`,
      image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1677847929i/51850968.jpg",
      genre: BOOK_GENRES.HORROR,
      language: "en",
      rating: 4.26,
      review: 10,
      price: 220,
      currency: 'Rs',
      countInStock: 300,
      pdf: '/pdfs/genres/Horror/As Darkness Breaks (Book One).pdf',
      userReviews: [
        { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
        { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
      ],  
    },
    {
      id: 3,
      title: "Bottled Nightmares (Book One)",
      author: "David Dwan",
      description: `An evil witch haunts Charlie's sleep, threatening to eat him and his brother up. When the witch appears in the real world and snatches Jack away, Charlie follows her into the Netherworld and, with the aid of a gorgon and a few slumbering friends, sets out to save not just his brother, but the Land of Nightmares itself.`,
      image: "https://www.obooko.com/images-cache/bottled-nightmares-horror-book-dwan-obooko-d7c7f0732a8592f99003bdcdfd664f4d.jpg",
      genre: BOOK_GENRES.HORROR,
      language: "en",
      rating: 4.26,
      review: 10,
      price: 340,
      currency: 'Rs',
      countInStock: 300,
      pdf: '/pdfs/genres/Horror/Bottled Nightmares (Book One).pdf',
      userReviews: [
        { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
        { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
      ],  
    },
    {
      id: 4,
      title: "Grosvenor Lane Ghost",
      author: "Jeremy Tyrrell",
      description: "Seventh-grader Castle Cranshaw, nicknamed Ghost, knows nothing about track when a former Olympian recruits him as a sprinter for one of the city's youth teams.",
      image: "https://m.media-amazon.com/images/I/71e3w5wdB+L._AC_UY327_FMwebp_QL65_.jpg",
      genre: BOOK_GENRES.HORROR,
      language: "en",
      rating: 4.26,
      review: 10,
      price: 340,
      currency: 'Rs',
      countInStock: 300,
      pdf: '/pdfs/genres/Horror/Grosvenor Lane Ghost.pdf',
      userReviews: [
        { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
        { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
      ],  
    },
    {
      id: 5,
      title: "Hidden Highway",
      author: "Tom Lichtenberg",
      description: `What happened at the end of Hidden? Warner Bros. After the Breathers break open the hatch, Claire and Zoe escape through the air duct but Ray cannot fit. Then, we see the splatter of blood, implying that the fearsome Breathers have ferociously killed him.`,
      image: "https://m.media-amazon.com/images/I/51YlnMzwv2L._SX342_SY445_.jpg",
      genre: BOOK_GENRES.HORROR,
      language: "en",
      rating: 4.26,
      review: 10,
      price: 500,
      currency: 'Rs',
      countInStock: 300,
      pdf: '/pdfs/genres/Horror/Hidden Highway.pdf',
      userReviews: [
        { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
        { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
      ],  
    },
  ],
  MYSTERY: [
    {
        id: 1,
        title: "Bicycle Shop Murder",
        author: "Robert Burton Robinson",
        description: `Greg Tenorly lives a quiet and lonely life in a small East Texas town, until he is selected as a juror for a murder trial. A beautiful, mysterious redhead befriends him, and seems to have a romantic interest. But is she merely using him to influence the outcome of the trial?`,
        image: "https://m.media-amazon.com/images/I/81I9JOVxumL._AC_UY327_FMwebp_QL65_.jpg",
        genre: BOOK_GENRES.MYSTERY,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 450,
        currency: 'Rs',
        countInStock: 300,
        pdf: `/pdfs/genres/Mystery/Bicycle Shop Murder.pdf`,
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
      {
        id: 2,
        title: "Death Stalks Her",
        author: "Peter C Byrnes",
        description: `Across Australia, one woman dies every week at the hands of a spouse, ex-spouse, friend, or a lover/former lover…in other words, someone she knew and trusted was responsible for her death.`,
        image: "https://m.media-amazon.com/images/I/515vL+agPjL._SX342_SY445_.jpg",
        genre: BOOK_GENRES.MYSTERY,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 130,
        currency: 'Rs',
        countInStock: 300,
        pdf: '/pdfs/genres/Mystery/Death Stalks Her.pdf',
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
      {
        id: 3,
        title: "Eleven Days An - Unexpected Love",
        author: "Lora Lindy",
        description: `After the death of her beloved cousin, Lana Andrews has to get away to be alone, to grieve. She rents a quaint little beach house in Plymouth MA. Little does she know she would meet that one special love, an unexpected love. That one true love is Mike Ramsey, and he's a U.S. Marshal and the beach house owner.`,
        image: "https://m.media-amazon.com/images/I/51ZliPk5zKL._SY445_SX342_.jpg",
        genre: BOOK_GENRES.MYSTERY,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 120,
        currency: 'Rs',
        countInStock: 300,
        pdf: '/pdfs/genres/Mystery/Eleven Days An - Unexpected Love.pdf',
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
      {
        id: 4,
        title: "Finding Lisa",
        author: "Sigrid Macdonald",
        description: `Finding Lisa is about having everything, losing something important, and re-evaluating life, love, and purpose as a result. It stands out from other stories of disappearance and searching because of its focus on a variety of themes beyond the event itself.`,
        image: "https://m.media-amazon.com/images/I/61ISzMtkVuL._SY522_.jpg",
        genre: BOOK_GENRES.MYSTERY,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 230,
        currency: 'Rs',
        countInStock: 300,
        pdf: '/pdfs/genres/Myster/Finding Lisa.pdf',
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
      {
        id: 5,
        title: "Gods Chosen",
        author: "Jeremy Gatlin",
        description: "The Chosen is a groundbreaking historical drama based on the life of Jesus, seen through the eyes of those who knew him. Set against the backdrop of Jewish oppression in first-century Israel, the series shares an authentic and intimate look at Jesus' revolutionary life and teachings.",
        image: "https://m.media-amazon.com/images/I/31ltc64UuuL._SY445_SX342_.jpg",
        genre: BOOK_GENRES.MYSTERY,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 300,
        currency: 'Rs',
        countInStock: 300,
        pdf: '/pdfs/genres/Mystery/Gods Chosen.pdf',
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
  ],
  HUMOR: [
    {
        id: 1,
        title: "Crafty Canine",
        author: "Linda Stone",
        description: "Gild the lily! Dress your pooch! Check out this delightful collection of canine fashions and accessories and stitch up any of these 11 happy, easy projects in a day or less: 2 different bags to carry dog-walking supplies, 1 bag to carry your dog with you while shopping, Sleeping mat, Bean bed, Portable bowl, Camouflage raincoat, Collar and neckerchief, Teething ball, & Picture frame. Make your dog proud to be seen with you!",
        image: "https://m.media-amazon.com/images/I/71WEWXnrejL._SY522_.jpg",
        genre: BOOK_GENRES.HUMOR,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 250,
        currency: 'Rs',
        countInStock: 300,
        pdf: `/pdfs/genres/Humor/Crafty Canine.pdf`,
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
      {
        id: 2,
        title: "Crown Crescent Chronicles",
        author: "Guy Bullock",
        description: "t's not much fun being a landlord when you have quirky tenants. In this hilarious chronicle Colin Bentley finds himself involved in the weird antics of some outlandish characters.",
        image: "https://m.media-amazon.com/images/I/71PrBHiuO5L._AC_UY327_FMwebp_QL65_.jpg",
        genre: BOOK_GENRES.HUMOR,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 130,
        currency: 'Rs',
        countInStock: 300,
        pdf: '/pdfs/genres/Humor/Crown Crescent Chronicles.pdf',userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
      {
        id: 3,
        title: "Innocent in the Afterlife",
        author: "Irene Soldatos",
        description: "Pope Innocent XIV drops dead three days into the job. But the afterlife, much like his reign, proves a bit of a disappointment. First, his guide, winged hat aside, is practically naked and thinks everything's a bit of a joke. ",
        image: "https://m.media-amazon.com/images/I/71AjWYNnmvL._AC_UY327_FMwebp_QL65_.jpg",
        genre: BOOK_GENRES.HUMOR,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 150,
        currency: 'Rs',
        countInStock: 300,
        pdf: '/pdfs/genres/Humor/Innocent in the Afterlife.pdf',
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
      {
        id: 4,
        title: "Lawyers, Laws, Justice and Judges",
        author: "Roger Himes",
        description: " From its early days, mystery fiction has drawn some of its most vivid characters and colorful stories from the annals of the law.",
        image: "https://m.media-amazon.com/images/I/71e3w5wdB+L._AC_UY327_FMwebp_QL65_.jpg",
        genre: BOOK_GENRES.HUMOR,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 300,
        currency: 'Rs',
        countInStock: 300,
        pdf: '/pdfs/genres/Humor/Lawyers, Laws, Justice and Judges.pdf',
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
      {
        id: 5,
        title: "One Clown Short",
        author: "Linda C Wright",
        description: "Mandy Maloney needs a job. She's had a successful run of flipping burgers at a popular fast food establishment, but the call to higher aspirations and a disapproving mother have finally forced her to flee to the classifieds.",
        image: "https://m.media-amazon.com/images/I/61wkzoWeWfL._AC_UY327_FMwebp_QL65_.jpg",
        genre: BOOK_GENRES.HUMOR,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 200,
        currency: 'Rs',
        countInStock: 300,
        pdf: '/pdfs/genres/Humor/One Clown Short.pdf',
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      }      
  ],
  ROMANCE: [
    {
        id: 1,
        title: "It Ends with Us",
        author: "Colleen Hoover",
        description: "Lily Bloom and her doomed romance with Ryle Kincaid and traces her past history growing up in an abusive home, her fall into an abusive relationship, and her escape from that relationship.",
        image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1688011813i/27362503.jpg",
        genre: BOOK_GENRES.ROMANCE,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 380,
        currency: 'Rs',
        countInStock: 300,
        pdf: `/pdfs/genres/Romance/It Ends with Us.pdf`,
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
      {
        id: 2,
        title: "Love on the Brain",
        author: "Christina Lauren",
        description: `What is the book Love on the Brain about Love on the Brain (2022) is a romance novel by Italian author Ali Hazelwood and follows the story of a neuroscientist, Dr. Bee Königswasser, who embarks on a career-high assignment of co-leading a project at NASA but has to contend with working alongside her old grad school nemesis, Levi Ward.`,
        image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTv6NA5nPx2tm-mKHf1ztRHZlZdPrqfqsA8xtgz_RVzOy6acLl2",
        genre: BOOK_GENRES.ROMANCE,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 200,
        currency: 'Rs',
        countInStock: 300,
        pdf: '/pdfs/genres/Romance/Love on the Brain.pdf',
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
      {
        id: 3,
        title: "November 9",
        author: "Colleen Hoover",
        description: "Fallon meets Ben, an aspiring novelist, the day before her scheduled cross-country move. Their untimely attraction leads them to spend Fallon's last day in Los Angeles together, and her eventful life becomes the creative inspiration Ben has always sought for his novel.",
        image: "https://m.media-amazon.com/images/I/71RBpTJkKaL._AC_UY327_FMwebp_QL65_.jpg",
        genre: BOOK_GENRES.ROMANCE,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 300,
        currency: 'Rs',
        countInStock: 300,
        pdf: '/pdfs/genres/Romance/November 9.pdf',
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
          { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
        ],  
      },
      {
        id: 4,
        title: "Pride and Prejudice",
        author: "Jane Austin",
        description: "Pride and Prejudice is a classic love story because it set the pattern for a modern popular love story, the story in which an independent-minded and fascinating woman is loved by a remote, powerful man. The attraction between the two of them is exhibited as hostility, at least for the first half of the book.",
        image: "https://m.media-amazon.com/images/I/81h36FJn2JL._AC_UY327_FMwebp_QL65_.jpg",
        genre: BOOK_GENRES.HUMOR,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 230,
        currency: 'Rs',
        countInStock: 300,
        pdf: '/pdfs/genres/Romance/Pride and Prejudice.pdf',
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'is a timeless masterpiece, skillfully navigating societal norms and love complexities, wrapped in Austen exquisite prose and rich character depth.' },
          { username: 'reader456', rating: 3.8, comment: ' remains an enduring classic, blending wit and romance against a backdrop of societal expectations, captivating readers with its timeless charm and insightful commentary on human nature.' }
        ],  
      },
      {
        id: 5,
        title: "Reminders of Him",
        author: "Colleen Hoover",
        description: "Reminders of Him (2022) is at once a conventional romance and a reimagination of the genre. Kenna Rowan, age 26, returns to her hometown near Denver after being in prison for five years. She is determined to have a relationship with her four-year-old daughter, Diem Landry.",
        image: "https://m.media-amazon.com/images/I/61lnZ5mPwNL._AC_UY327_FMwebp_QL65_.jpg",
        genre: BOOK_GENRES.ROMANCE,
        language: "en",
        rating: 4.26,
        review: 10,
        price: 250,
        currency: 'Rs',
        countInStock: 300,
        pdf: '/pdfs/genres/Romance/Reminders of Him.pdf',
        userReviews: [
          { username: 'user123', rating: 4.5, comment: 'delicately navigates the tender complexities of love and loss, weaving a touching tale of resilience and healing.' },
          { username: 'reader456', rating: 3.8, comment: '"Through heartfelt prose and emotional depth, Reminders of Him navigates the complexities of grief and healing, offering a poignant reflection on love and loss."' }
        ],  
      },
  ],
  SCIENCE: 
  [   
{
    id: 1,
    title: "Ellandra",
    author: "T S Alexander",
    description: "The Land has been at peace for a generation now. Still, evil has been busy, and toils where least expected. A tall, mysterious woman disturbs the rest of two legends biding time in the Tall Wood. Alphonse Dorn, the Big Man, and Bailey Ott, the sensate, set out to discover the woman's origin.",
    image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1585680202i/52855165.jpg",
    genre: BOOK_GENRES.SCIENCE,
    language: "en",
    rating: 4.26,
    review: 10,
    price: 300,
    currency: 'Rs',
    countInStock: 300,
    pdf: `/pdfs/genres/Science/Ellandra.pdf`,
    userReviews: [
      { username: 'user123', rating: 4.5, comment: 'conjures a mesmerizing world steeped in magic and mystery, entwining an enchanting quest with poignant themes of destiny and courage.' },
      { username: 'reader456', rating: 3.8, comment: 'takes readers on an exhilarating journey through a land brimming with magic, destiny, and the power of choice.' }
    ],  
  },
  {
    id: 2,
    title: "Homeland",
    author: "Cory Doctrow",
    description: "Here is the story of two families in small-town Basque country, pitted against each other by the ideology and violence of the terrorist group ETA (Basque Homeland and Liberty), from the unrelentingly grim 1980s to October 2011 when the group proclaimed an end to its savage insurgency.",
    image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1631983063i/50027.jpg",
    genre: BOOK_GENRES.SCIENCE,
    language: "en",
    rating: 4.26,
    review: 10,
    price: 290,
    currency: 'Rs',
    countInStock: 300,
    pdf: '/pdfs/genres/Science/Homeland.pdf',
    userReviews: [
      { username: 'user123', rating: 4.5, comment: '"Homeland" intricately intertwines personal struggles with political upheaval, offering a riveting tale of loyalty and societal change.' },
      { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
    ],  
  },
  {
    id: 3,
    title: "Man in the Moon",
    author: "Bradley Pearce",
    description: `"The infant Man in the Moon (named for the Moon Clipper, an extraterrestrial airship that disguises itself as a moon at night) is hidden away by his parents in order to escape the nefarious Pitch, "the King of Nightmares," renowned for "plundering planets, extinguishing stars, and scuttling every airship that crossed."`,
    image: "https://m.media-amazon.com/images/I/61KbElMFCeL._SX342_SY445_.jpg",
    genre: BOOK_GENRES.SCIENCE,
    language: "en",
    rating: 4.26,
    review: 10,
    price: 230,
    currency: 'Rs',
    countInStock: 300,
    pdf: '/pdfs/genres/Science/Man in the Moon.pdf',
    userReviews: [
      { username: 'user123', rating: 4.5, comment: '"Man in the Moon" unfolds a whimsical yet touching tale, blending imagination and heart in a cosmic adventure that sparks wonder with each turn of the page.' },
      { username: 'reader456', rating: 3.8, comment: '"Man in the Moon" crafts a delightful journey across celestial landscapes, weaving a touching narrative that invites readers to embrace the magic of the unknown.' }
    ],  
  },
  {
    id: 4,
    title: "Renegade Robot",
    author: "Tom Lichtenberg",
    description: `The Alien Detective Agency series of reading books, featuring Jack Swift and Wanda Darkstar, are for children and young adults aged 8 to 14 and over who are struggling to read`,
    image: "https://m.media-amazon.com/images/I/81h36FJn2JL._AC_UY327_FMwebp_QL65_.jpg",
    genre: BOOK_GENRES.SCIENCE,
    language: "en",
    rating: 4.26,
    review: 10,
    price: 350,
    currency: 'Rs',
    countInStock: 300,
    pdf: '/pdfs/genres/Science/Renegade Robot.pdf',
    userReviews: [
      { username: 'user123', rating: 4.5, comment: '"Renegade Robot" races through a thrilling world where robots rebel, delivering a gripping tale of friendship and identity in a high-tech landscape.' },
      { username: 'reader456', rating: 3.8, comment: '"Renegade Robot" is a fast-paced saga of friendship and rebellion in a thrilling futuristic realm.' }
    ],  
  },
  {
    id: 5,
    title: "Rose Red",
    author: "Stephanie Van Orman",
    description: "My Life at Rose Red is a rare document, one that gives us an unusual view of daily life among the aristocracy in the early 1900s, a window into one womans hidden emotional torment, and a record of the mysterious events at Rose Red that scandalized Seattle society at the timeevents that can",
    image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1660692215i/61999349.jpg",
    genre: BOOK_GENRES.SCIENCE,
    language: "en",
    rating: 4.26,
    review: 10,
    price: 150,
    currency: 'Rs',
    countInStock: 300,
    pdf: '/pdfs/genres/Science/Rose Red.pdf',
    userReviews: [
      { username: 'user123', rating: 4.5, comment: '"Rose Red" spins a captivating tale of familial curses and hidden magic, entwining mystery and suspense with enchanting prose. ' },
      { username: 'reader456', rating: 3.8, comment: '"Rose Red" intricately weaves a haunting tapestry of family lore, magic, and the allure of the unknown, leaving an indelible mark long after the final page.' }
    ],  
  },
  ],
  THRILLER: [
   
{
    id: 1,
    title: "Four Weeks to Live",
    author: "Don McGraw",
    description: "Four Weeks to Live presents a gripping narrative ticking away in real-time, as characters navigate life's complexities and confront their deepest fears when confronted with a limited timeline. An intense journey of self-discovery, relationships, and the urgency of embracing life in the face of impending mortality.",
    image: "https://m.media-amazon.com/images/I/81QYEb6YnVL._AC_UY327_FMwebp_QL65_.jpg",
    genre: BOOK_GENRES.THRILLER,
    language: "en",
    rating: 4.26,
    review: 10,
    price: 200,
    currency: 'Rs',
    countInStock: 300,
    pdf: `/pdfs/genres/Thriller/Four Weeks to Live.pdf`,
    userReviews: [
      { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
      { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
    ],  
  },
  {
    id: 2,
    title: "Hammer of God",
    author: "Reginald Cook",
    description: "Hammer of God crafts a riveting saga, blending cosmic intrigue with the raw essence of humanity, exploring the collision between faith, science, and the enigmatic forces shaping our existence. A compelling odyssey through existential questions and the search for meaning in the vastness of the universe.",
    image: "https://upload.wikimedia.org/wikipedia/en/8/81/HammerOfGod.jpg",
    genre: BOOK_GENRES.THRILLER,
    language: "en",
    rating: 4.26,
    review: 10,
    price: 200,
    currency: 'Rs',
    countInStock: 300,
    pdf: '/pdfs/genres/Thriller/Hammer of God.pdf',
    userReviews: [
      { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
      { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
    ],  
  },
  {
    id: 3,
    title: "Illusion of Luck",
    author: "Greg Tenorly",
    description: "Illusion of Luck unravels a gripping narrative, delving into the intricacies of chance, fate, and the human quest for fortune. Through intertwining stories of serendipity and choice, it explores the blurred lines between luck, perseverance, and the illusions we construct around both.",
    image: "https://m.media-amazon.com/images/I/61jqiXV5kIL._SY522_.jpg",
    genre: BOOK_GENRES.THRILLER,
    language: "en",
    rating: 4.26,
    review: 10,
    price: 18.26,
    currency: 'Rs',
    countInStock: 300,
    pdf: '/pdfs/genres/Thriller/Illusion of Luck.pdf',
    userReviews: [
      { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
      { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
    ],  
  },
  {
    id: 4,
    title: "Lady in Red",
    author: "Bradley Pearce",
    description: "Lady in Red spins an evocative tale of mystery and passion, weaving the allure of a clandestine romance against the backdrop of societal expectations and hidden desires. A mesmerizing journey through secrets, love, and the intoxicating power of forbidden attraction.",
    image: "https://m.media-amazon.com/images/I/51wJHXQCr6L._SX342_SY445_.jpg",
    genre: BOOK_GENRES.THRILLER,
    language: "en",
    rating: 4.26,
    review: 10,
    price: 250,
    currency: 'Rs',
    countInStock: 300,
    pdf: '/pdfs/genres/Thriller/Lady in Red.pdf',
    userReviews: [
      { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
      { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
    ],  
  },
  {
    id: 5,
    title: "Root of Unity",
    author: "SL Huang",
    description: "Root of Unity delves into the captivating world of mathematics, exploring the profound significance of roots of unity across diverse mathematical landscapes. From their elegant geometric representations to their fundamental role in number theory and applications in fields like signal processing and physics, this book navigates the intricacies of these mathematical entities. With clarity and depth, it unveils the beauty of roots of unity, offering insights into their connections to symmetry, equations, and their pervasive influence across various disciplines. An essential read for mathematicians, scientists, and enthusiasts seeking a deeper understanding of this foundational concept.",
    image: "https://archive.org/download/RootOfUnity-SLHuang/Root%20of%20Unity%20CC0%20cover.jpg",
    genre: BOOK_GENRES.THRILLER,
    language: "en",
    rating: 4.26,
    review: 10,
    price: 320,
    currency: 'Rs',
    countInStock: 300,
    pdf: '/pdfs/genres/Thriller/Root of Unity',
    userReviews: [
      { username: 'user123', rating: 4.5, comment: 'Great story, loved the characters!' },
      { username: 'reader456', rating: 3.8, comment: 'Interesting plot but pacing was a bit slow.' }
    ],  
  },
  ]
}
export { data_sample, BOOK_GENRES };







